
name: CRDA CI Build

on:
  pull_request:
    branches: [ master ]
    
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Run Linter
      run: bash qa/run-linter.sh;
  docstyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Run Docstyle
      run: bash qa/check-docstyle.sh
  detect-common-errors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name:  Run Detect common errors
      run: bash qa/detect-dead-code.sh
  detect-dead-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Run Detect dead code 
      run: bash qa/detect-dead-code.sh
  Cyclomatic-complexity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Run Cyclomatic Complexity Check
      run: bash qa/measure-cyclomatic-complexity.sh --fail-on-error
  Maintainablity-index:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Run Maintainablity index check
      run:  bash qa/measure-maintainability-index.sh --fail-on-error
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Run Unit Tests
      run:  bash qa/actions-run-tests.sh
